#!/bin/bash

VOL=$(cmdline_value "vol")
if [ "$VOL" != "" ]; then
   echo "Setting sound volume: ${VOL}%"
   for SCONTROL in {"Master","PCM","Front","Surround","Center","CD","Video"}; do
     /usr/bin/amixer -q sset $SCONTROL ${VOL}% unmute 2>/dev/null
   done
else
   echo "Setting sound volume: 90%"
   for SCONTROL in {"Master","PCM","Front","Surround","Center","CD","Video"}; do
     /usr/bin/amixer -q sset $SCONTROL 90% unmute 2>/dev/null
   done
fi
