#!/bin/bash

#
# This script support some ZenLive's cheatcodes.
#

. /usr/lib/liblinuxlive

# passwd: Change root's password at startup
newrootpass="`cmdline_value passwd`"
if [ "$newrootpass" = "ask" ]; then
    echo -ne "\nEnter new password for root: "
    read -s newrootpass
fi

if [ ! "$newrootpass" = "" ]; then
    echo "root:$newrootpass" | /usr/sbin/chpasswd
fi

# ldconfig: Updates dynamic library cache. Useful when new modules are
# added to the live cd.
if [ "`cmdline_parameter ldconfig`" ]; then
    [[ -x /sbin/ldconfig ]] && /sbin/ldconfig
fi

if [ "`cmdline_parameter nonfree`" ]; then
    /etc/rc.d/xakra-nonfree start
elif [ ! "`cmdline_parameter noxconf`" ]; then
    /etc/rc.d/xakra start
fi

# lang: Override default language
lang="`cmdline_value lang`"
if [ "$lang" ]; then
    echo "$lang ISO-8859-1" > /etc/locale.gen
    echo "$lang UTF-8" >> /etc/locale.gen
    locale-gen
	[[ "`locale -a | grep -w $lang`" ]] && \
	sed -i -e 's/^ *\(LOCALE=\).*$/\1$lang.UTF-8/' /etc/rc.conf
fi

# Make firefox match OS locale
if [ -w /usr/lib/firefox/greprefs/all.js ]; then
    sed -i -e 's/pref("intl.locale.matchOS",                 false);/pref("intl.locale.matchOS",                 true);/g' /usr/lib/firefox-3.0/greprefs/all.js
fi

# Make thunderbird match OS locale
#if [ -w /usr/lib/thunderbird/greprefs/all.js ]; then
#    sed -i -e 's/pref("intl.locale.matchOS",                 false);/pref("intl.locale.matchOS",                 true);/g' /usr/lib/thunderbird/greprefs/all.js
#fi


# keyb: Override default keyboard layout
keyb="`cmdline_value keyb`"
if [ "$keyb" ]; then
   if [ -x /bin/loadkeys ]; then
 	/bin/loadkeys $keyb
   fi
fi

session="`cmdline_value session`"
if [ "$session" != "" ]; then
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/X11/xinit/xinitrc
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/skel/.xinitrc
fi

chmod 0440 /etc/sudoers
update-desktop-database -q

#chown arch:users -R /home/arch
#chown root:root -R /root

acerone=$(cmdline_parameter acerone)
if [ "$(acerone)" ]; then
	/etc/rc.d/acerone
fi
