#!/bin/bash

#
# This script support some ZenLive's cheatcodes.
#

. /usr/lib/liblinuxlive

# passwd: Change root's password at startup
newrootpass="`cmdline_value passwd`"
if [ "$newrootpass" = "ask" ]; then
    echo -ne "\nEnter new password for root: "
    read -s newrootpass
fi

if [ ! "$newrootpass" = "" ]; then
    echo "root:$newrootpass" | /usr/sbin/chpasswd
fi

AUTOCMD=$(cmdline_value "autoexec" | tr "~" " ")
if [ "$AUTOCMD" != "" ]; then
   echo "starting autoexec command: su --login -c \"$AUTOCMD\""
   su --login -c "$AUTOCMD"
fi

# ldconfig: Updates dynamic library cache. Useful when new modules are
# added to the live cd.
if [ "`cmdline_parameter ldconfig`" ]; then
    [[ -x /sbin/ldconfig ]] && /sbin/ldconfig
fi

if [ "`cmdline_parameter nonfree`" ]; then
	if [ -e "/etc/X11/xorg.conf" ]; then
    		/etc/rc.d/xakra-nonfree start
	else
		/etc/rc.d/xakra start
    		/etc/rc.d/xakra-nonfree start
	fi
elif [ ! "`cmdline_parameter noxconf`" ]; then
	if [ -e "/etc/rc.d/xorg.conf" ]; then
		echo "no auto config needed"
	else
		/etc/rc.d/xakra start
	fi
fi

# lang: Override default language
lang="`cmdline_value lang`"
if [ "$lang" ]; then
    locale-gen
    # Make firefox match OS locale
    #if [ -f /usr/lib/firefox-3.0/defaults/preferences/firefox-I10n.js ]; then
    # 	echo "pref("general.useragent.locale", "$lang")" > /usr/lib/firefox-3.0/defaults/preferences/firefox-I10n.js
    #fi
fi

# Make thunderbird match OS locale
#if [ -w /usr/lib/thunderbird-2.0/greprefs/all.js ]; then
#    sed -i -e 's/pref("intl.locale.matchOS",                 false);/pref("intl.locale.matchOS",                 true);/g' /usr/lib/thunderbird/greprefs/all.js
#fi


# keyb: Override default keyboard layout
keyb="`cmdline_value keyb`"
if [ "$keyb" ]; then
   if [ -x /bin/loadkeys ]; then
 	/bin/loadkeys $keyb
   fi
fi

session="`cmdline_value session`"
if [ "$session" != "" ]; then
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/X11/xinit/xinitrc
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/skel/.xinitrc
fi

chmod 0440 /etc/sudoers

if [ -x /usr/bin/update-desktop-database ]; then
	update-desktop-database -q
fi

#chown arch:users -R /home/arch
#chown root:root -R /root

acerone=$(cmdline_parameter acerone)
if [ "$acerone" ]; then
	/etc/rc.d/acerone
fi

fah=$(cmdline_parameter fah)
if [ "$fah" ]; then
	/etc/rc.d/foldingathome start
fi