#!/bin/bash
# Activate numlock on the console

case $1 in
	start)
  for t in 1 2 3 4 5 6 7 8 ; do
    setleds +num < /dev/tty$t > /dev/null
  done
  ;;
  stop)
  for t in 1 2 3 4 5 6 7 8 ; do
    setleds -num < /dev/tty$t > /dev/null
  done
  ;;
	*)
		echo "Usage: rc.numlock {start|stop}"
		exit 1
		;;
esac

