#!/bin/bash

#
# This file contains workarounds for certain hardware
#

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
	start)
	
	stat_busy "Inspecting hardware"

	# check platform
	/opt/chakra/bin/platform-detect &>/dev/null
	if [ $? -ne 0 ]; then	
		printhl "This machine seems to be a desktop computer"

		# create status file for postinstall
		touch /tmp/platform-desktop
	else
		printhl "This machine seems to be a laptop computer"

		# create status file for postinstall
		touch /tmp/platform-laptop

	fi

	# check cpu
	check_cpu=$(uname -p)
	printhl "Running on a $check_cpu"

	# try to fix some problems with realtek network cards
	check_8139_modules=$(lsmod | grep 8139cp || lsmod | grep 8139too)
	if [ -n "$check_8139_modules" ]; then

		problems_with_8139cp=$(dmesg | grep -i 'Try the "8139too" driver instead')
		problems_with_8139too=$(dmesg | grep -i 'Try the "8139cp" driver instead')
		if [ -n "$problems_with_8139cp" ]; then
			printhl "Trying to fix broken realtek network driver"
			rmmod 8139cp &>/dev/null
			touch /etc/modprobe.d/realtek_blacklist &>/dev/null
			echo "blacklist 8139cp" >> /etc/modprobe.d/realtek_blacklist &>/dev/null
			modprobe 8139too &>/dev/null
		fi
		if [ -n "$problems_with_8139too" ]; then
			printhl "Trying to fix broken realtek network driver"
			rmmod 8139too &>/dev/null
			touch /etc/modprobe.d/realtek_blacklist &>/dev/null 
			echo "blacklist 8139too" >> /etc/modprobe.d/realtek_blacklist &>/dev/null
			modprobe 8139cp &>/dev/null
		fi
	fi

	# check available network devices
	check_network=$(cat /proc/net/dev | awk '{ print  $1 }' | egrep '^(lo|eth|ath|wlan|ppp|ra|tap)' | cut -d: -f1 | sed -e :a -e '$!N;s/\n/ /')	
	printhl "Available network devices: $check_network"

	stat_done
	;;
	stop)
	;;
	restart)
	$0 stop
	sleep 1
	$0 start
	;;
	*)
	echo "usage: $0 {start|stop|restart}"
esac
