#!/bin/bash

#
# This script support some ZenLive's cheatcodes.
#

. /usr/lib/liblinuxlive

# passwd: Change root's password at startup
newrootpass="`cmdline_value passwd`"
if [ "$newrootpass" = "ask" ]; then
    echo -ne "\nEnter new password for root: "
    read -s newrootpass
fi

if [ ! "$newrootpass" = "" ]; then
    echo "root:$newrootpass" | /usr/sbin/chpasswd
fi

AUTOCMD=$(cmdline_value "autoexec" | tr "~" " ")
if [ "$AUTOCMD" != "" ]; then
   echo "starting autoexec command: su --login -c \"$AUTOCMD\""
   su --login -c "$AUTOCMD"
fi

# ldconfig: Updates dynamic library cache. Useful when new modules are
# added to the live cd.
if [ "`cmdline_parameter ldconfig`" ]; then
    [[ -x /sbin/ldconfig ]] && /sbin/ldconfig
fi

# Make thunderbird match OS locale
#if [ -w /usr/lib/thunderbird-2.0/greprefs/all.js ]; then
#    sed -i -e 's/pref("intl.locale.matchOS",                 false);/pref("intl.locale.matchOS",                 true);/g' /usr/lib/thunderbird/greprefs/all.js
#fi

depmod -a

chmod 0440 /etc/sudoers

if [ -x /usr/bin/update-desktop-database ]; then
	update-desktop-database -q
fi

if [ -x /usr/bin/update-mime-database ]; then
	update-mime-database /usr/share/mime
fi

#chown arch:users -R /home/arch
#chown root:root -R /root

acerone=$(cmdline_parameter acerone)
if [ "$acerone" ]; then
	/etc/rc.d/acerone
fi

fah=$(cmdline_parameter fah)
if [ "$fah" ]; then
	/etc/rc.d/foldingathome start
fi

ARCH=$(uname -m)
if [  ${ARCH} = x86_64 ]; then
	sed -i 's|i686|x86_64|g' /etc/pacman.d/mirrorlist
	sed -i 's|i686|x86_64|g' /etc/pacman.d/kdemodmirrorlist
fi

sed -i 's/^.*DAEMONS=.*/DAEMONS=(syslog-ng hal config wicd slim)/' /etc/rc.conf 
chmod -x /etc/rc.d/archlive
