#!/bin/bash

export GTK_PATH="/opt/lib32/usr/lib/gtk-2.0"
export PANGO_RC_FILE="/opt/lib32/config/pango/pangorc"
export GCONV_PATH="/opt/lib32/usr/lib/gconv"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/lib32/lib:/opt/lib32/usr/lib"
export GDK_PIXBUF_MODULE_FILE="/opt/lib32/config/gdk/gdk-pixbuf.loaders"

cd /opt/chromium-browser
./chrome --enable-plugins "$@"
