#!/bin/bash
WORKDIR=.working
DATE="$(date +%F)"
ISONAME=archiso-live-${DATE}.iso

makeiso() 
{
	mkarchiso -f all "${WORKDIR}" "${ISONAME}"
}

makesquashfs()
{
	mkarchiso -f squash "${WORKDIR}"
}

makeimg()
{
	mkarchiso -f imgprepare "${WORKDIR}"
	mkarchiso -f img "${WORKDIR}" "${ISONAME}"
}

clean()
{
	rm -rf "${WORKDIR}" "${ISONAME}"
}

if [ "${1}" = "makeiso" ]; then
	makeiso
fi

if [ "${1}" = "makeimg" ]; then
	makeimg
fi

if [ "${1}" = "clean" ]; then
	clean
fi

if [ "${1}" = "squash" ]; then
	makesquashfs
fi