#!/bin/bash

#
# This script support some ZenLive's cheatcodes.
#

. /usr/lib/liblinuxlive

# passwd: Change root's password at startup
newrootpass="`cmdline_value passwd`"
if [ "$newrootpass" = "ask" ]; then
    echo -ne "\nEnter new password for root: "
    read -s newrootpass
fi

if [ ! "$newrootpass" = "" ]; then
    echo "root:$newrootpass" | /usr/sbin/chpasswd
fi

# ldconfig: Updates dynamic library cache. Useful when new modules are
# added to the live cd.
if [ "`cmdline_parameter ldconfig`" ]; then
    [[ -x /sbin/ldconfig ]] && /sbin/ldconfig
fi

# lang: Override default language
lang="`cmdline_value lang`"
if [ "$lang" ]; then
    echo "${lang} ISO-8859-1" >> /etc/locale.gen
    echo "${lang}.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
	[[ "`locale -a | grep -w ${lang}.utf8`" ]] && \
	echo "LOCALE=${lang}.utf8" >> /etc/rc.conf
fi

# Make firefox match OS locale
if [ -w /usr/lib/firefox/greprefs/all.js ]; then
    sed -i -e 's/pref("intl.locale.matchOS",                 false);/pref("intl.locale.matchOS",                 true);/g' /usr/lib/firefox-3.0/greprefs/all.js
fi

# Make thunderbird match OS locale
#if [ -w /usr/lib/thunderbird/greprefs/all.js ]; then
#    sed -i -e 's/pref("intl.locale.matchOS",                 false);/pref("intl.locale.matchOS",                 true);/g' /usr/lib/thunderbird/greprefs/all.js
#fi


# keyb: Override default keyboard layout
keyb="`cmdline_value keyb`"
if [ "$keyb" ]; then
   if [ -x /bin/loadkeys ]; then
 	/bin/loadkeys $keyb
   fi
fi


# noxconf: Skip X (video & keyboard) auto configuration
if [ ! "`cmdline_parameter noxconf`" ]; then
    [[ -x /usr/sbin/videoconfig ]] && /usr/sbin/videoconfig silent
fi


# numlock: Override default numlock settings
numlock="`cmdline_value numlock`"
if [ "$numlock" = "on" ]; then
    [ -x /usr/bin/numlockx ] && /usr/bin/numlockx on
    #[ -w /etc/X11/gdm/Init/Default ] && sed -i 's/.*\(\[ -x \/usr\/bin\/numlockx \].*\)/\1/' /etc/X11/gdm/Init/Default
else
    [ -x /usr/bin/numlockx ] && /usr/bin/numlockx off
    #[ -w /etc/X11/gdm/Init/Default ] && sed -i 's/.*\(\[ -x \/usr\/bin\/numlockx \].*\)/#\1/' /etc/X11/gdm/Init/Default
fi

session="`cmdline_value session`"
if [ "$session" != "" ]; then
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/X11/xinit/xinitrc
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/skel/.xinitrc
fi

update-desktop-database -q
#autologin: Enables autologin
if [ "`cmdline_value autologin`" ]; then
   	/etc/rc.d/adduser "${autologin}"
   	/bin/su ${autologin} -l -c "/bin/bash --login  -c /usr/bin/startx > /dev/null 2>/dev/null"
else
	chmod 0440 /etc/sudoers
   	/bin/su arch -l -c "/bin/bash --login  -c /usr/bin/startx > /dev/null 2>/dev/null"
fi
