#!/bin/bash

#
# icons-cache
#
# args: [stop]
#

. /etc/splash/"${SPLASH_THEME}"/icons.conf

icon_size=32
icon_size_small=16

daemons=(
	acpid
	alsa
	cups
	samba
	mysqld
	netfs
	nfsd
	sensors
	smartd
)

stats=( start stop fail )

theme_images="/etc/splash/${SPLASH_THEME}/images"

mkdir -p "${spl_cachedir}/arch-banner-icons"

# separator line painted on splash daemon [re]start
if [ -e ${spl_cachedir}/fail_fbsplash-dummy ]; then
	ln -sfT "${theme_images}"/separator-red.png "${spl_cachedir}/arch-banner-icons/fbsplash-dummy.init"
else
	ln -sfT "${theme_images}"/separator.png "${spl_cachedir}/arch-banner-icons/fbsplash-dummy.init"
fi

ii=${icon_size}x${icon_size}

for name in "${daemons[@]}" ; do
	# icons painted on daemon actions
	ln -sfT "${theme_images}"/dummy.png "${spl_cachedir}/arch-banner-icons/${name}"
	# icons painted on splash daemon [re]start
	ln -sfT "${theme_images}"/dummy.png "${spl_cachedir}/arch-banner-icons/${name}.init"
done

for name in "${daemons[@]}" ; do
	icon="/usr/share/icons/${ICON_THEME}/${ii}/$( eval echo \"\$ICON_${name}\" )"
	[ -f "${icon}" ] || continue
	ln -sfT "${icon}" "${spl_cachedir}/arch-banner-icons/${name}"
done

if [ -n "${1}" ]; then
	daemons=( $( splash_svclist_get "${1}" ) )

	for name in "${daemons[@]}" ; do
		icon="/usr/share/icons/${ICON_THEME}/${ii}/$( eval echo \"\$ICON_${name}\" )"
		[ -f "${icon}" ] || continue
		ln -sfT "${icon}" "${spl_cachedir}/arch-banner-icons/${name}.init"
	done
fi

ii=${icon_size_small}x${icon_size_small}

for name in "${stats[@]}" ; do
	icon="/usr/share/icons/${ICON_THEME}/${ii}/$( eval echo \"\$ICON_${name}\" )"
	[ -f "${icon}" ] || icon="${theme_images}"/dummy.png
	ln -sfT "${icon}" "${spl_cachedir}/arch-banner-icons/${name}"
done

