#!/bin/bash

hwdetect_platform()
{
	/opt/chakra/bin/platform-detect.sh
	if [ $? -ne 0 ]
	then
		printhl "This machine seems to be a desktop computer"
		# create status file for postinstall
		touch /tmp/platform-desktop
	else
		printhl "This machine seems to be a laptop computer"
		# create status file for postinstall
		touch /tmp/platform-laptop
	fi
}
