#!/bin/bash
# convert directory tree into .sqfs compressed file
# which can be used as a LiveCD module
#
# Author: Tomas M. <http://www.linux-live.org>
#

PATH=.:$(dirname $0):/usr/lib:$PATH
. liblinuxlive || exit 1

if [ ! -d "$1" -o "$2" = "" ]; then
   echo
   echo "Convert directory tree into .sqfs compressed module"
   echo "usage: $0 source_directory output_file.sqfs [ -skipcheck ]"
   exit 1
fi


mksquashfs "$1" "$2"
if [ $? != 0 ]; then echo "error building compressed image"; exit 1; fi

chmod 0444 "$2"
echo -e "\ndone OK"
