#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
	start)
		stat_busy "Setting up non-free graphics drivers"
		/opt/xakra/bin/xakra-nonfree
	;;
	stop)
	;;
	restart)
	$0 stop
	sleep 1
	$0 start
	;;
	*)
	echo "usage: $0 {start|stop|restart}"  
esac 
