#!/bin/bash
WORKDIR=.working
DATE="$(date +%F)"
ISONAME=wolvix-${DATE}.iso

makeiso() 
{
	mkarchiso -c wolvix -f all "${WORKDIR}" "${ISONAME}"
}

makeimg()
{
	mkarchiso -c wolvix -f imgprepare "${WORKDIR}"
	mkarchiso -c wolvix -f img "${WORKDIR}" "${ISONAME}"
}

clean()
{
	rm -rf "${WORKDIR}" "${ISONAME}"
}

if [ "${1}" = "makeiso" ]; then
	makeiso
fi

if [ "${1}" = "makeimg" ]; then
	makeimg
fi

if [ "${1}" = "clean" ]; then
	clean
fi