#! /bin/bash

# Copyright Alex <blackcat.myako@gmail.com>. 
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#
#      You should have received a copy of the GNU General Public License
#      along with this program; if not, write to the Free Software
#      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
########################## LiveInstall gui ##########################

# Disclaimer message from above menu
export DISCLAIMER='
<window title="LiveInstall" window_position="1" icon-name="gtk-dialog-warning">

	<vbox>

		<text use-markup="true">
			<label>"<b>Disclaimer</b>"</label>
		</text>

		<text>
			<label>"LiveInstall is still under development and comes under no warranty, either express or implied."</label>
		</text>

		<hbox>

			<button ok>
      			<action type="closewindow">DISCLAIMER</action>
    		</button>

		</hbox>

	</vbox>
	
</window> 
'

# About message from above menu
export ABOUT='
<window title="LiveInstall" window_position="1" icon-name="gtk-about">

	<vbox>

		<text use-markup="true">
			<label>"<b>About</b>"</label>
		</text>

		<text>
			<label>"LiveInstall will install ZenLive to the harddisk.

Copyright Tatzi (blackcat.myako@gmail.com).

LiveInstall is released under the GNU General Public License."
			</label>
		</text>

		<hbox>

			<button ok>
				<action type="closewindow">ABOUT</action>
			</button>

		</hbox>

	</vbox>
	
</window> 
'

# Success message at the end of whole procedure
export DONE='
<window title="LiveInstall" icon-name="gtk-info">

	<vbox>

		<text use-markup="true">
			<label>"<b>The installation of ZenLive was succesfull !</b>"</label>
		</text>

		<text use-markup="true">
			<label>"
ZenLive is now installed to the harddisk. You can restart your computer and login into ZenWalk."
			</label>		
		</text>
		
		<hbox>
		
			<button ok>
				<action type="exit">=quit</action>    	
    		</button>
		
		</hbox>
	
	</vbox>

</window> 
'

# Error message at the end of whole procedure
export ERROR='
<window title="LiveInstall" window_position="1" icon-name="gtk-dialog-error">

	<vbox>

		<text use-markup="true">
			<label>"<b>Install failed !</b>"</label>
		</text>

		<text>
			<label>"Sorry... The installation of ZenLive is failed...
Please, exit LiveInstall, verify your settings and try again.	"</label>
		</text>

		<hbox>

			<button>
				<input file icon="gtk-find"></input>
				<label>View Install log... </label>
				<action type="launch">LiveInstallLOG</action>
			</button>	
		
			<button ok>
				<action type="exit">=quit</action>
    		</button>

		</hbox>

	</vbox>

</window> 
'

export LiveInstallLOG='
<window title="Logfile Monitor" window_position="1" icon-name="gtk-find">

	<vbox>

		<text>
			<label>"
			"</label>
		</text>

		<text>
			<input>cat /var/log/liveinstall.log</input>
		</text>

		<hbox>

			<button ok>
				<action type="closewindow">LiveInstallLOG</action>
			</button>

		</hbox>

	</vbox>

</window> 
'

# Main window
export MAIN_DIALOG='
<window title="LiveInstall" window_position="1" icon-name="liveinstall">
<vbox>
	<menubar>
		<menu>
			<menuitem stock="gtk-quit">
				<action type="exit">=quit</action>
			</menuitem>
		<label>File</label>
		</menu>
		<menu>
			<menuitem icon="gtk-dialog-warning">
				<label>Disclaimer</label>
				<action type="launch">DISCLAIMER</action>
			</menuitem>			
			<menuitem icon="gtk-about">
				<label>About</label>
				<action type="launch">ABOUT</action>
			</menuitem>
		<label>Help</label>
		</menu>
	</menubar>

	<notebook labels="Main|Partition|Software Setup|Custom Setup">
		<hbox>
			<frame>
				<text use-markup="true">
					<label>"<b>Welcome to LiveInstall !</b>"</label>
				</text>
				
				<pixmap>
					<input file>/usr/share/pixmaps/liveinstall.png</input>
				</pixmap>
				<text use-markup="true">
					<label>"
					"</label>
				</text>
				<text>
					<label>"This utility will help you to install your Zenwalk Live environment.Please consult the instructions from the help menu above."</label>
				</text>
								
			</frame>
		</hbox>
		<hbox>
			<frame>
			<table> 
				<label>Partitions...</label>
				<input>lilolist</input>
				<variable>SELSYS</variable>
			</table>
			</frame>
		</hbox>
		<vbox>
			<frame>
				<text use-markup="true">
					<label>"<b>User Setup</b>"</label>
				</text>
				<hbox>
					<text>
						<label>"      Username : "</label>
					</text>
					<text width-chars="2">
						<label>" "</label>
					</text>		
					<entry activates_default="true">
		      				<default>linux</default>
						<variable>USRNAME</variable>				
					</entry>	
				</hbox>
				<hbox>
					<checkbox>
						<label>Autologin at Start</label>
						<default>no</default>
						<visible>disabled</visible>
						<variable>AUTOLOGGDM</variable>	
					</checkbox>
					<text width-chars="25">
						<label>" "</label>
					</text>
				</hbox>
				<hbox>
					<checkbox>
						<label>ZenLite Desktop Design</label>
						<default>yes</default>
						<variable>ZENLITEDESK</variable>	
					</checkbox>
					<text width-chars="21">
						<label>" "</label>
					</text>
				</hbox>
				<text use-markup="true">
					<label>"
					"</label>
				</text>
				<text use-markup="true">
					<label>"<b>ZenWalk Software</b>"</label>
				</text>
				<hbox>
					<checkbox>
						<label>Install Zencore System</label>
						<default>no</default>
						<variable>ZENCORE_INSTALL</variable>	
						<action>if true clear:ZENBASE_INSTALL</action>
						<action>if true clear:ZENWALK_INSTALL</action>
						<action>if true clear:ZENALL_INSTALL</action>
						<action>if true disable:RLEFT</action>	
						<action>if true disable:RRIGHT</action>	
					</checkbox>
					<text width-chars="22">
						<label>" "</label>
					</text>
				</hbox>
				<hbox>
					<checkbox>
						<label>Install Zenwalk Base System</label>
						<default>no</default>
						<variable>ZENBASE_INSTALL</variable>	
						<action>if true clear:ZENCORE_INSTALL</action>
						<action>if true clear:ZENWALK_INSTALL</action>
						<action>if true clear:ZENALL_INSTALL</action>
						<action>if true disable:RLEFT</action>	
						<action>if true disable:RRIGHT</action>	
					</checkbox>
					<text width-chars="18">
						<label>" "</label>
					</text>
				</hbox>
				<hbox>
					<checkbox>
						<label>Install Zenwalk System</label>
						<default>no</default>
						<variable>ZENWALK_INSTALL</variable>
						<action>if true clear:ZENCORE_INSTALL</action>
						<action>if true clear:ZENBASE_INSTALL</action>
						<action>if true clear:ZENALL_INSTALL</action>	
						<action>if true disable:RLEFT</action>	
						<action>if true disable:RRIGHT</action>	
					</checkbox>
					<text width-chars="22">
						<label>" "</label>
					</text>
				</hbox>
				<hbox>
					<checkbox>
						<label>Custom Setup</label>
						<default>yes</default>
						<variable>ZENALL_INSTALL</variable>	
						<action>if true clear:ZENCORE_INSTALL</action>
						<action>if true clear:ZENBASE_INSTALL</action>
						<action>if true clear:ZENWALK_INSTALL</action>
						<action>if true enable:RLEFT</action>	
						<action>if true enable:RRIGHT</action>	
					</checkbox>
					<text width-chars="28">
						<label>" "</label>
					</text>
				</hbox>
			</frame>
		</vbox>
		<hbox>
			<frame>
			<notebook labels="Install list|Remove list">
				<vbox>
				 	 <tree icon="netpkg-tree-item" rules_hint="true" exported_column="1">
						<label> Install these Modules</label>
						<input>Rgetleftlist</input>
						<height>200</height>
						<width>300</width>
						<variable>RLEFT</variable>
						<action>Rmoveright</action>
						<action type="clear">RLEFT</action>
						<action type="refresh">RLEFT</action>
						<action type="clear">RRIGHT</action>
						<action type="refresh">RRIGHT</action>
						<action signal="cursor_changed" type="clear">DESC</action>
		        		<action signal="cursor_changed" type="refresh">DESC</action>
			  		</tree>
						<table>
							<height>75</height>
							<variable>DESC</variable>
							<input>getdescription_left</input>      
						</table>
				</vbox>
	    			<vbox>
					  <tree icon="netpkg-tree-item" rules_hint="true" exported_column="1">
						<label> Not install these Modules</label>
						<input>Rgetrightlist</input>
						<height>200</height>
						<width>300</width>
						<variable>RRIGHT</variable>
						<action>Rmoveleft</action>
						<action type="clear">RLEFT</action>
						<action type="refresh">RLEFT</action>
						<action type="clear">RRIGHT</action>
						<action type="refresh">RRIGHT</action>
						<action signal="cursor_changed" type="clear">DESC2</action>
			        	<action signal="cursor_changed" type="refresh">DESC2</action>
					  </tree>
						<table>
							<height>75</height>
							<variable>DESC2</variable>
							<input>getdescription_right</input>      
						</table>
      				</vbox>
			</notebook>
			</frame>
		</hbox>
	</notebook>
	<hbox>		
		<button>
			<input file icon="gtk-apply"></input>
			<action>install</action>
		</button>			
		<button cancel>
			<action type="exit">=quit</action>
		</button>
	</hbox>
</vbox>
</window> 
'

