# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.startup.homepage", "http://archlinux.org/");
user_pref("startup.homepage_override_url", "");
user_pref("startup.homepage_welcome_url", "");
