diff -rud packETH-1.6/src/Makefile packETH-1.6-patched/src/Makefile
--- packETH-1.6/src/Makefile	2008-02-20 11:25:13.000000000 -0300
+++ packETH-1.6-patched/src/Makefile	2009-01-30 21:56:23.000000000 -0300
@@ -22,7 +22,7 @@
 prefix = /usr
 includedir = /usr/src/include
 
-INSTALL = /usr/bin/install -c
+INSTALL = /usr/bin/env install -D -c
 INSTALL_DATA = ${INSTALL} -m 644
 INSTALL_PREFIX = /usr
 
