#!/bin/sh

# fdisk-l

# Get the general disk info returned by 'fdisk -l' applied to device $1
#
LANG=C fdisk -l $1 | grep -A3 "$1:"

# -> something like:
#Disk /dev/sda: 16.1 GB, 16179527680 bytes
#255 heads, 63 sectors/track, 1967 cylinders
#Units = cylinders of 16065 * 512 = 8225280 bytes
#Disk identifier: 0x0001c0c5
