#!/bin/sh

# get-cd

# Get a list of cd-like devices.
# Return the device basename

for dev in $( cat /proc/sys/dev/cdrom/info 2>/dev/null | head -n 3 | \
        tail -n 1 | cut -d ":" -f 2 ); do
    echo "${dev}"
done
