#!/bin/sh

# get-lvm

# Get a list of lvm partitions which could, potentially be mounted.
# Return the device basename

for lvmd in $( ls /dev/mapper 2>/dev/null | grep -v control ); do
    echo "${lvmd}"
done
