#!/bin/sh

# gparted-available

# Test whether gparted is available on the system.

if [ -z "${DISPLAY}" ]; then
    echo "X not running"
elif which gparted &>/dev/null; then
    echo -n '^OK^'
else
    echo "No gparted"
fi
