#!/bin/sh

# Install grub to device $1
INSTALL=/tmp/install

mount --bind /proc ${INSTALL}/proc
mount --bind /sys ${INSTALL}/sys
mount --bind /dev ${INSTALL}/dev
cat /proc/mounts | grep ${INSTALL} | sed "s|${INSTALL}|/|" | \
    sed "s|//|/|" >${INSTALL}/etc/mtab
chroot ${INSTALL} /sbin/grub-install --no-floppy $1
: >${INSTALL}/etc/mtab
umount ${INSTALL}/dev
umount ${INSTALL}/sys
umount ${INSTALL}/proc
