#! /bin/sh
# larch-tidy  - Finish off copy part of installation

INSTALL=/tmp/install

# Make special directories
mkdir -m 1777 ${INSTALL}/tmp
mkdir ${INSTALL}/media
mkdir ${INSTALL}/sys
mkdir ${INSTALL}/proc

mkdir ${INSTALL}/mnt
find /mnt -maxdepth 1 -type d -exec mkdir ${INSTALL}{} \;

mkdir ${INSTALL}/dev
mknod ${INSTALL}/dev/console c 5 1
mknod ${INSTALL}/dev/null c 1 3
mknod ${INSTALL}/dev/zero c 1 5

# Test for larch-4
if [ -f ${INSTALL}/etc/rc.sysinit0 ]; then
# larch-4
    # Get these files in their 'original' versions
    cp -af /.livesys/system/etc/{rc.sysinit,rc.shutdown,inittab} ${INSTALL}/etc
    # Remove extra larch 'rc.' scripts
    rm -f ${INSTALL}/etc/{rc.sysinit0,rc.shutdown2,rc.shutdown3}
    # Remove extra larch entry in PATH
    rm -f ${INSTALL}/etc/profile.d/larch.sh

    # Remove live-specific packages
    for p in initcpio_larch larchin archin; do
        pacman -r ${INSTALL} -R ${p} 2>/dev/null
    done

else
# larch-5
    # Get the 'original' version of saved files in /etc
    # (inittab, rc.sysinit, rc.shutdown)
    for fs in ${INSTALL}/etc/*.larchsave; do
        mv -f ${fs} ${fs%.larchsave}
    done

    # Remove live-specific packages
    for p in larch-live larchin larchin-syscalls; do
        pacman -r ${INSTALL} -R ${p} 2>/dev/null
    done

    # Remove larch live specific package upgrade ignores
    if grep "#---LARCH-IGNORE---" ${INSTALL}/etc/pacman.conf &>/dev/null; then
        sed "/#+++LARCH-IGNORE+++/,/#---LARCH-IGNORE---/ d" \
                -i ${INSTALL}/etc/pacman.conf
    fi

    # Remove any files and directories intended only for the live system,
    # perform any other custom tweaks
    if [ -f /.livesys/larch0 ]; then
        . /.livesys/larch0
    fi
fi
