#!/bin/sh

# part-format

# Format a partition (argument $1), file-system type $2, options $3

fmtext3 ()
{
    mke2fs -j $1

    if [ "$1" != "/" ]; then
        tune2fs -m 1 $1
    fi

    opts="$2"

    while [ -n "${opts}" ]; do
        o=${opts:0:1}
        opts=${opts:1}
        case ${o} in
            I ) # directory indexing
                if ! tune2fs -O dir_index $1; then
                    echo -n "Directory indexing failed"
                    return 1
                fi ;;
            C ) # disable boot-time checks
                if ! tune2fs -c 0 -i 0 $1; then
                    echo -n "Disabling boot-time checks failed"
                    return 1
                fi ;;
            F ) # full journalling
                if ! tune2fs -O has_journal -o journal_data $1; then
                    echo -n "Full journalling failed"
                    return 1
                fi ;;
            i ) ;;
            c ) ;;
            f ) ;;

            * ) echo -n "Unknown ext3 option: ${o}"
                return 1 ;;
        esac
    done
    return 0
}

p=$1
f=$2
o=$3
case ${f} in
    ext3 ) fmtext3 ${p} ${o} ;;
    reiserfs ) mkreiserfs -q ${p} ;;
    ext2 ) mke2fs ${p} ;;
    jfs ) mkfs.jfs -q ${p} ;;
    xfs ) mkfs.xfs -f ${p} ;;
    ext4 ) mkfs.ext4 ${p} ;;
    * ) echo -n "Bad arguments: ${p} ${f} ${o}"
        false ;;
esac

if [ $? -eq 0 ]; then
    echo -n '^OK^'
fi
