#!/bin/sh

# rmpart

# Remove the partitions (argument $2) on the given (argument $1) device
# using parted.

if parted -s $1 rm $2; then
    echo -n '^OK^'
else
    echo -n "Couldn't remove partition $1$2"
fi
