#!/bin/bash
WORKDIR=.working
DATE="$(date +%F)"
CDNAME="archiso-testing"
ISONAME=$CDNAME-${DATE}.iso


makeinstall()
{
	mkarchiso -c $CDNAME -m $1 -f install "${WORKDIR}"
}

makeiso() 
{
	mkarchiso -c $CDNAME -m $1 -f all "${WORKDIR}" "${ISONAME}"
}

makesquashfs()
{
	mkarchiso -c $CDNAME -m $1 -f squash "${WORKDIR}"
}

makeimg()
{
	mkarchiso -c $CDNAME -m $1 -f imgprepare "${WORKDIR}"
	mkarchiso -c $CDNAME -m $1 -f img "${WORKDIR}" "${ISONAME}"
}

clean()
{
	rm -rf "${WORKDIR}" "${ISONAME}"
}


if [ "${1}" = "makeinstall" ]; then
	makeinstall $2
fi

if [ "${1}" = "makeiso" ]; then
	makeiso $2
fi

if [ "${1}" = "makeimg" ]; then
	makeimg $2
fi

if [ "${1}" = "clean" ]; then
	clean
fi

if [ "${1}" = "squash" ]; then
	makesquashfs $2
fi