#!/bin/bash
WORKDIR=.working
DATE="$(date +%F)"
ISONAME=archiso-live-${DATE}.iso

makeiso() 
{
	mkarchiso -f all "${WORKDIR}" "${ISONAME}"
}

clean()
{
	rm -rf "${WORKDIR}" "${ISONAME}"
}

if [ "${1}" = "makeiso" ]; then
	makeiso
fi

if [ "${1}" = "clean" ]; then
	clean
fi